version: "3.7"

services:
  server:
    image: 'c-local-dev'
    container_name: "c-socket-server"
    stdin_open: true
    tty: true
    command: bash
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - ./server/:/home/user/app
    networks:
      server:
        ipv4_address: 10.5.0.5

  client:
    image: 'c-local-dev'
    container_name: "c-socket-client"
    stdin_open: true
    tty: true
    command: bash
    environment:
      - PORT=${PORT:-3000}
      - HOST=${HOST:-10.5.0.5}
    volumes:
      - ./client/:/home/user/app
    networks:
      server:
        ipv4_address: 10.5.0.6

networks:
  server:
    name: c-socket-server
    external: true
