version: "3.7"

services:
  server:
    image: 'c-socket-server'
    container_name: "c-socket-server"
    build:
      context: .
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    working_dir: /home/user/app
    stdin_open: true
    tty: true
    command: bash
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - ./server/:/home/user/app
    networks:
      server:
        ipv4_address: 10.5.0.5

  client:
    image: 'c-socket-client'
    container_name: "c-socket-client"
    build:
      context: .
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    working_dir: /home/user/app
    stdin_open: true
    tty: true
    command: bash
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - PORT=${PORT:-3000}
      - HOST=${HOST:-10.5.0.5}
    volumes:
      - ./client/:/home/user/app
    networks:
      server:
        ipv4_address: 10.5.0.6

networks:
  server:
    name: c-socket-server
    external: true
